/**
 * @file vcu_can_rx.c
 *
 * @brief This source file was generated by cantools version 41.0.2 Sat Mar 21 12:43:18 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "vcu_can_rx.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int vcu_can_rx_inv_drive_cmd_pack(
    uint8_t *dst_p,
    const struct vcu_can_rx_inv_drive_cmd_t *src_p,
    size_t size)
{
    uint16_t torque_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    torque_req = (uint16_t)src_p->torque_req;
    dst_p[0] |= pack_left_shift_u16(torque_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(torque_req, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->speed_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->speed_req, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->inverter_enable, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->control_mode, 1u, 0x0eu);

    return (8);
}

int vcu_can_rx_inv_drive_cmd_init(struct vcu_can_rx_inv_drive_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct vcu_can_rx_inv_drive_cmd_t));

    return 0;
}

int16_t vcu_can_rx_inv_drive_cmd_torque_req_encode(double value)
{
    return (int16_t)(value / 0.1);
}

bool vcu_can_rx_inv_drive_cmd_torque_req_is_in_range(int16_t value)
{
    return ((value >= -2000) && (value <= 2000));
}

uint16_t vcu_can_rx_inv_drive_cmd_speed_req_encode(double value)
{
    return (uint16_t)(value - -5000.0);
}

bool vcu_can_rx_inv_drive_cmd_speed_req_is_in_range(uint16_t value)
{
    return (value <= 15000u);
}

uint8_t vcu_can_rx_inv_drive_cmd_inverter_enable_encode(double value)
{
    return (uint8_t)(value);
}

bool vcu_can_rx_inv_drive_cmd_inverter_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t vcu_can_rx_inv_drive_cmd_control_mode_encode(double value)
{
    return (uint8_t)(value);
}

bool vcu_can_rx_inv_drive_cmd_control_mode_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int vcu_can_rx_inv_feedback_unpack(
    struct vcu_can_rx_inv_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t actual_torque;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_torque = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    actual_torque |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->actual_torque = (int16_t)actual_torque;
    dst_p->actual_speed = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->actual_speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->motor_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fault_code = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int vcu_can_rx_inv_feedback_init(struct vcu_can_rx_inv_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct vcu_can_rx_inv_feedback_t));

    return 0;
}

double vcu_can_rx_inv_feedback_actual_torque_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool vcu_can_rx_inv_feedback_actual_torque_is_in_range(int16_t value)
{
    return ((value >= -2000) && (value <= 2000));
}

double vcu_can_rx_inv_feedback_actual_speed_decode(uint16_t value)
{
    return ((double)value + -5000.0);
}

bool vcu_can_rx_inv_feedback_actual_speed_is_in_range(uint16_t value)
{
    return (value <= 15000u);
}

double vcu_can_rx_inv_feedback_motor_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool vcu_can_rx_inv_feedback_motor_temp_is_in_range(uint8_t value)
{
    return (value <= 190u);
}

double vcu_can_rx_inv_feedback_fault_code_decode(uint8_t value)
{
    return ((double)value);
}

bool vcu_can_rx_inv_feedback_fault_code_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int vcu_can_rx_inv_multi_data_unpack(
    struct vcu_can_rx_inv_multi_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t phase_a_current;
    uint16_t phase_b_current;
    uint16_t phase_c_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mux_switch = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    switch (dst_p->mux_switch) {

    case 0:
        phase_a_current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        phase_a_current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->phase_a_current = (int16_t)phase_a_current;
        break;

    case 1:
        phase_b_current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        phase_b_current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->phase_b_current = (int16_t)phase_b_current;
        break;

    case 2:
        phase_c_current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        phase_c_current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->phase_c_current = (int16_t)phase_c_current;
        break;

    default:
        break;
    }

    return (0);
}

int vcu_can_rx_inv_multi_data_init(struct vcu_can_rx_inv_multi_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct vcu_can_rx_inv_multi_data_t));

    return 0;
}

double vcu_can_rx_inv_multi_data_mux_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool vcu_can_rx_inv_multi_data_mux_switch_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

double vcu_can_rx_inv_multi_data_phase_a_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool vcu_can_rx_inv_multi_data_phase_a_current_is_in_range(int16_t value)
{
    return ((value >= -5000) && (value <= 5000));
}

double vcu_can_rx_inv_multi_data_phase_b_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool vcu_can_rx_inv_multi_data_phase_b_current_is_in_range(int16_t value)
{
    return ((value >= -5000) && (value <= 5000));
}

double vcu_can_rx_inv_multi_data_phase_c_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool vcu_can_rx_inv_multi_data_phase_c_current_is_in_range(int16_t value)
{
    return ((value >= -5000) && (value <= 5000));
}
