/**
 * @file vcu_can_rx.h
 *
 * @brief This header file was generated by cantools version 41.0.2 Sat Mar 21 12:43:18 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef VCU_CAN_RX_H
#define VCU_CAN_RX_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define VCU_CAN_RX_INV_DRIVE_CMD_FRAME_ID (0x210u)
#define VCU_CAN_RX_INV_FEEDBACK_FRAME_ID (0x1a0u)
#define VCU_CAN_RX_INV_MULTI_DATA_FRAME_ID (0x300u)

/* Frame lengths in bytes. */
#define VCU_CAN_RX_INV_DRIVE_CMD_LENGTH (8u)
#define VCU_CAN_RX_INV_FEEDBACK_LENGTH (8u)
#define VCU_CAN_RX_INV_MULTI_DATA_LENGTH (8u)

/* Extended or standard frame types. */
#define VCU_CAN_RX_INV_DRIVE_CMD_IS_EXTENDED (0)
#define VCU_CAN_RX_INV_FEEDBACK_IS_EXTENDED (0)
#define VCU_CAN_RX_INV_MULTI_DATA_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define VCU_CAN_RX_INV_DRIVE_CMD_CYCLE_TIME_MS (10u)
#define VCU_CAN_RX_INV_FEEDBACK_CYCLE_TIME_MS (10u)
#define VCU_CAN_RX_INV_MULTI_DATA_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define VCU_CAN_RX_INV_DRIVE_CMD_INVERTER_ENABLE_DISABLE_CHOICE (0u)
#define VCU_CAN_RX_INV_DRIVE_CMD_INVERTER_ENABLE_ENABLE_CHOICE (1u)

#define VCU_CAN_RX_INV_DRIVE_CMD_CONTROL_MODE_TORQUE_CONTROL_CHOICE (0u)
#define VCU_CAN_RX_INV_DRIVE_CMD_CONTROL_MODE_SPEED_CONTROL_CHOICE (1u)
#define VCU_CAN_RX_INV_DRIVE_CMD_CONTROL_MODE_VOLTAGE_CONTROL_CHOICE (2u)

#define VCU_CAN_RX_INV_FEEDBACK_FAULT_CODE_NO_FAULT_CHOICE (0u)
#define VCU_CAN_RX_INV_FEEDBACK_FAULT_CODE_OVER_CURRENT_CHOICE (1u)
#define VCU_CAN_RX_INV_FEEDBACK_FAULT_CODE_OVER_TEMP_CHOICE (2u)
#define VCU_CAN_RX_INV_FEEDBACK_FAULT_CODE_RESOLVER_ERROR_CHOICE (3u)

/* Frame Names. */
#define VCU_CAN_RX_INV_DRIVE_CMD_NAME "INV_DriveCmd"
#define VCU_CAN_RX_INV_FEEDBACK_NAME "INV_Feedback"
#define VCU_CAN_RX_INV_MULTI_DATA_NAME "INV_MultiData"

/* Signal Names. */
#define VCU_CAN_RX_INV_DRIVE_CMD_TORQUE_REQ_NAME "TorqueReq"
#define VCU_CAN_RX_INV_DRIVE_CMD_SPEED_REQ_NAME "SpeedReq"
#define VCU_CAN_RX_INV_DRIVE_CMD_INVERTER_ENABLE_NAME "InverterEnable"
#define VCU_CAN_RX_INV_DRIVE_CMD_CONTROL_MODE_NAME "ControlMode"
#define VCU_CAN_RX_INV_FEEDBACK_ACTUAL_TORQUE_NAME "ActualTorque"
#define VCU_CAN_RX_INV_FEEDBACK_ACTUAL_SPEED_NAME "ActualSpeed"
#define VCU_CAN_RX_INV_FEEDBACK_MOTOR_TEMP_NAME "MotorTemp"
#define VCU_CAN_RX_INV_FEEDBACK_FAULT_CODE_NAME "FaultCode"
#define VCU_CAN_RX_INV_MULTI_DATA_MUX_SWITCH_NAME "Mux_Switch"
#define VCU_CAN_RX_INV_MULTI_DATA_PHASE_A_CURRENT_NAME "PhaseA_Current"
#define VCU_CAN_RX_INV_MULTI_DATA_PHASE_B_CURRENT_NAME "PhaseB_Current"
#define VCU_CAN_RX_INV_MULTI_DATA_PHASE_C_CURRENT_NAME "PhaseC_Current"

/**
 * Signals in message INV_DriveCmd.
 *
 * All signal values are as on the CAN bus.
 */
struct vcu_can_rx_inv_drive_cmd_t {
    /**
     * Requested torque to the motor
     *
     * Range: -2000..2000 (-200..200 Nm)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t torque_req;

    /**
     * Range: 0..15000 (-5000..10000 RPM)
     * Scale: 1
     * Offset: -5000
     */
    uint16_t speed_req;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t inverter_enable;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t control_mode;
};

/**
 * Signals in message INV_Feedback.
 *
 * All signal values are as on the CAN bus.
 */
struct vcu_can_rx_inv_feedback_t {
    /**
     * Range: -2000..2000 (-200..200 Nm)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t actual_torque;

    /**
     * Range: 0..15000 (-5000..10000 RPM)
     * Scale: 1
     * Offset: -5000
     */
    uint16_t actual_speed;

    /**
     * Range: 0..190 (-40..150 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t motor_temp;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fault_code;
};

/**
 * Signals in message INV_MultiData.
 *
 * Multiplexed message containing 3-phase AC currents
 *
 * All signal values are as on the CAN bus.
 */
struct vcu_can_rx_inv_multi_data_t {
    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mux_switch;

    /**
     * Range: -5000..5000 (-500..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_a_current;

    /**
     * Range: -5000..5000 (-500..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_b_current;

    /**
     * Range: -5000..5000 (-500..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_c_current;
};

/**
 * Pack message INV_DriveCmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int vcu_can_rx_inv_drive_cmd_pack(
    uint8_t *dst_p,
    const struct vcu_can_rx_inv_drive_cmd_t *src_p,
    size_t size);

/**
 * Init message fields to default values from INV_DriveCmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int vcu_can_rx_inv_drive_cmd_init(struct vcu_can_rx_inv_drive_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t vcu_can_rx_inv_drive_cmd_torque_req_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_drive_cmd_torque_req_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t vcu_can_rx_inv_drive_cmd_speed_req_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_drive_cmd_speed_req_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t vcu_can_rx_inv_drive_cmd_inverter_enable_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_drive_cmd_inverter_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t vcu_can_rx_inv_drive_cmd_control_mode_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_drive_cmd_control_mode_is_in_range(uint8_t value);

/**
 * Unpack message INV_Feedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int vcu_can_rx_inv_feedback_unpack(
    struct vcu_can_rx_inv_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from INV_Feedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int vcu_can_rx_inv_feedback_init(struct vcu_can_rx_inv_feedback_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_feedback_actual_torque_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_feedback_actual_torque_is_in_range(int16_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_feedback_actual_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_feedback_actual_speed_is_in_range(uint16_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_feedback_motor_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_feedback_motor_temp_is_in_range(uint8_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_feedback_fault_code_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_feedback_fault_code_is_in_range(uint8_t value);

/**
 * Unpack message INV_MultiData.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int vcu_can_rx_inv_multi_data_unpack(
    struct vcu_can_rx_inv_multi_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from INV_MultiData.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int vcu_can_rx_inv_multi_data_init(struct vcu_can_rx_inv_multi_data_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_multi_data_mux_switch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_multi_data_mux_switch_is_in_range(uint8_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_multi_data_phase_a_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_multi_data_phase_a_current_is_in_range(int16_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_multi_data_phase_b_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_multi_data_phase_b_current_is_in_range(int16_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double vcu_can_rx_inv_multi_data_phase_c_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool vcu_can_rx_inv_multi_data_phase_c_current_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
